### ISSUE TITLE
Vite manifest not found at

### ISSUE THREAD

**Issue by madfortech** [LaravelDaily/laravel-permission-ui#14]
![Screenshot 2022-12-20 103738](https://user-images.githubusercontent.com/21261716/208588334-86ea7d44-f40a-48f8-8d38-a92ab359a84a.jpg)

I think this package only Vite user, please add web pack mix or any future plan add webpack mix

**Comment by PovilasKorop** [comment]
@madfortech as the main readme says, Status update: package idea abandoned.
